name: Gcloud CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      RUN_REGION: us-central1
      SERVICE_NAME: myapp


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml


      - name: Checkout
        uses: actions/checkout@master

         # Setup gcloud CLI
      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
           version: 'latest'
           service_account_email: ${{ secrets.SA_EMAIL }}
           service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}


          # Docker build
      - name: Build
        run: |
           docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME .


        # Build Cloud Run project
      -name: Build
        run: |
           gcloud builds submit --tag gcr.io/users-management-305009/myapp


        # Deploy image to Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy $SERVICE_NAME \
          --region $RUN_REGION \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
          --platform managed \
          --allow-unauthenticated \
          --project $PROJECT_ID
