name: MyApp CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Docker Build
        run: docker build -t newapp:1.0

      - name: Docker Run
        run: docker run -d -p 8080:8080 newapp:1.0 .

      - name: Googl Cloud Bild
        run: gcloud builds submit --tag gcr.io/users-management-305009/myapp

      - name: Googl Cloud Deploy
        run: gcloud run deploy --image gcr.io/users-management-305009/myapp --platform managed

